### ISSUE TITLE
crash when binding to a tcp socket

### ISSUE THREAD

**Issue by BrainDamage** [OpenMusicKontrollers/synthpod#49]
to reproduce:
synthpod_dummy -l tcp://localhost:9090
( altough it happens with any backend )

gdb gives a stacktrace that's different between the backends, perhaps there's a memory corruption spillover?
with dummy:
```
Program received signal SIGSEGV, Segmentation fault.
_sandbox_io_send (io=io@entry=0x55555568e2d0, index=index@entry=0, size=size@entry=0, protocol=0, buf=buf@entry=0x0) at ../sandbox_ui.lv2/sandbox_io.h:268
268	../sandbox_ui.lv2/sandbox_io.h: File o directory non esistente
(gdb) thread apply all bt
Thread 1 (Thread 0x7ffff79b3d00 (LWP 1014053)):
#0  _sandbox_io_send (io=io@entry=0x55555568e2d0, index=index@entry=0, size=size@entry=0, protocol=0, buf=buf@entry=0x0) at ../sandbox_ui.lv2/sandbox_io.h:268
#1  0x000055555555d7a6 in _sandbox_io_deinit.constprop.0 (io=0x55555568e2d0, terminate=true) at ../sandbox_ui.lv2/sandbox_io.h:536
#2  0x000055555555e17d in sandbox_master_free (sb=0x55555568e2d0) at ../sandbox_ui.lv2/sandbox_master.c:62
#3  sandbox_master_free (sb=0x55555568e2d0) at ../sandbox_ui.lv2/sandbox_master.c:58
#4  sandbox_master_new (driver=0x55555558c970 <handle.15540.lto_priv+816>, data=0x55555558c640 <handle.15540.lto_priv>, minimum=16777216) at ../sandbox_ui.lv2/sandbox_master.c:53
#5  bin_init.constprop.0 (sample_rate=<optimized out>, bin=0x55555558c640 <handle.15540.lto_priv>) at ../bin/synthpod_bin.c:419
#6  0x0000555555558fb6 in main (argc=3, argv=0x7fffffffc588) at ../bin/synthpod_dummy.c:608
```
with jack:
```
thread 3 "synthpod_jack" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7ffff6f9c700 (LWP 1010803)]
0x00007ffff7e7042c in read () from /usr/lib/libc.so.6
(gdb) thread apply all bt

Thread 3 (Thread 0x7ffff6f9c700 (LWP 1010803)):
#0  0x00007ffff7e7042c in read () from /usr/lib/libc.so.6
#1  0x00007ffff7bc5d8f in ?? () from /usr/lib/libjack.so.0
#2  0x00007ffff7bcac79 in ?? () from /usr/lib/libjack.so.0
#3  0x00007ffff7bc4b3d in ?? () from /usr/lib/libjack.so.0
#4  0x00007ffff7b7f4cf in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff7e7f2d3 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff7fcd700 (LWP 1010802)):
#0  0x00007ffff7b85c45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00007ffff7bc5610 in ?? () from /usr/lib/libjack.so.0
#2  0x00007ffff7bbce36 in ?? () from /usr/lib/libjack.so.0
#3  0x00007ffff7bc4b3d in ?? () from /usr/lib/libjack.so.0
#4  0x00007ffff7b7f4cf in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007ffff7e7f2d3 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff712b740 (LWP 1010791)):
#0  0x00007ffff7b80a87 in __pthread_timedjoin_ex () from /usr/lib/libpthread.so.0
```

**Comment by ventosus** [comment]
> synthpod_dummy -l tcp://localhost:9090

That flag does not even exists, and TCP sockets have never been supported in the first place.
What version is this, where did you get it from ?
